### ISSUE TITLE
Probleme mit Anzeige in Inserttag-Übersicht

### ISSUE THREAD

**Issue by madmaharaja** [terminal42/contao-inserttags#10]
Ich habe in einer Installation mittlerweile über 500 Inserttags mithilfe dieser Erweiterung erstellt. Die Erweiterung ist mir eine Riesenhilfe -- vielen Dank!
Allerdings funktioniert die Übersichtsanzeige nicht richtig. Es werden mir IMMER die ersten 500 Inserttags in der Übersicht angezeigt -- egal, ob ich mir bei "Anzeigen" 30er-Grüppchen einstelle oder "Alle" einstelle und dann die zweite Gruppe (501–549) auswähle (siehe Screenshot). <img width="745" alt="screenshot-inserttag-uebersicht" src="https://cloud.githubusercontent.com/assets/3133710/8766769/cc859c12-2e44-11e5-97e6-7e7a093b023d.png">
Neu laden, Cache leeren, ausloggen – alles probiert, das Problem bleibt. Ich kann leider nicht sagen, ob das Problem von Anfang an bestand oder erst jetzt mit der hohen Anzahl an Inserttags. Allerdings, um auszuschließen, dass es sich um einen generellen Bug in meiner Installation (Contao 3.4.5) handelt, habe ich mir z.B. die Übersichten in anderen Modulen angeschaut -- z.B. bei der Nachrichtenübersicht funktioniert die Paginierung in der Anzeige einwandfrei.

Bei der Gelegenheit: Wäre es möglich, eine alphabetische Sortierung der Inserttags und eine Suchmöglichkeit nach Namen der Platzhalter in der Übersicht zu implementieren (damit man sich z.B. nur die Inserttags ansehen kann, die "foobar" im Namen enthalten)?

**Comment by aschempp** [comment]
Die InsertTags haben eine spezifische Reihenfolge, weil zwei mit demselben Namen sich überschreiben (je nach Konfiguration). Entsprechend ist eine Pagination gar nicht möglich, das entsprechende Feld sollte nicht angezeigt werden…

**Comment by madmaharaja** [comment]
Danke für die Rückmeldung. Ich verstehe nicht ganz, wie die Reihenfolge (in der Datenbank?) funktionell mit der Sortierung im Backend zusammenhängt und warum das eine Paginierung ausschließt -- aber muss ich als "Nicht-Programmierer" ja auch nicht wirklich. Aber dann stellt sich mir als Anwender die Frage, wie man ohne Paginierung, bei gleichzeitig maximaler Anzeige von 500 Datensätzen im Backend, die Datensätze jenseits der 500 bearbeiten kann/soll? Zwei Vorschläge von mir (was zumindest aus meiner Sicht eine große Hilfe wäre und die Arbeit mit vielen Inserttags übersichtlicher gestalten würde):
1.) Wenn es in dieser Erweiterung "Archive" oder "Kategorien" als Parent-Element gäbe, sodass man in der Inserttag-Übersicht auf oberster Ebene zunächst nur die "Archive" angezeigt bekommt und erst auf der zweiten Ebene dann die entsprechend "einsortierten" Inserttags.
2.) Wenn man die Möglichkeit hätte, die Tags in der Übersicht nach den Namen der Platzhalter zu durchsuchen (derzeit kann man nur "Beschreibung" und "Ersatz" durchsuchen) und sie optional auch alphabetisch zu sortieren (oder geht das wegen der "spezifischen Reihenfolge und zwei Tags mit demselben Namen auch nicht?).

**Comment by aschempp** [comment]
> Ich verstehe nicht ganz, wie die Reihenfolge (in der Datenbank?) funktionell mit der Sortierung im Backend zusammenhängt und warum das eine Paginierung ausschließt

Das ist eine technische Limitierung von Contao. Eine Ansicht die manuell sortiert werden kann (blauer Pfeil) kann nicht gleichzeitig eine Pagination haben.

Generell denke ich aber, dass die Erweiterung nicht dafür gemacht ist 500 InsertTags zu verwalten… das ist sicherlich auch nicht besonders performant. Vermutlich wärst du mit einem eigenen Modul genau für deine Anforderungen besser bedient.

**Comment by madmaharaja** [comment]
Bezügl. manueller Sortierung und Pagination: Bei der CSS-Bearbeitung im Backend geht's aber.
Und bislang kann ich was Performance betrifft bei +500 Inserttags, auch beim Laden von Seiten, auf denen sich ca. 150 Inserttags auf einmal befinden, keine Leistungseinbußen oder langsame Ladezeiten bemerken.
Ich wäre jedenfalls an einem eigenen Modul interessiert und war diesbezüglich schon mit einem deiner Kollegen in Kontakt. Aber mir scheint, eure Agentur richtet sich weniger an Freiberufler/Privatpersonen, sondern eher an Agenturen/Unternehmen, oder?

**Comment by aschempp** [comment]
Wenn du's technisch wissen willst, die InsertTags sind eine Darstellung im Mode 5 (Baumstruktur), und die CSS ein Mode 4 (Parent-Child). Das geht hier nicht, glaube mir ;-)
