### ISSUE TITLE
BE view

### ISSUE THREAD

**Issue by MoniqueHahnefeld** [terminal42/contao-inserttags#11]
hi :)
I have a ugly backend view in my contao 3.5.4 installation:
![contao-inserttags-bug](https://cloud.githubusercontent.com/assets/2779282/10663147/6e2977d2-78b9-11e5-9944-9809be1c380e.png)

can you reproduce it or do you need more info?

**Comment by aschempp** [comment]
I'm not actively using the module, so I can't reproduce it. If you can, please provide a pull request to fix it.

**Comment by MoniqueHahnefeld** [comment]
ok should be possible in next time...

**Comment by MoniqueHahnefeld** [comment]
strange. i had installed the version 1.9.2 an no .htaccess was inside, whether it is here. was maybe a composer issue
https://github.com/terminal42/contao-inserttags/tree/1.9.2/html
