### ISSUE TITLE
Contao 4 adjustment in composer.json

### ISSUE THREAD

**Issue by Defcon0** [terminal42/contao-inserttags#13]
Hello,

I just forked your module in order to adjust the composer.json for contao 4. It seems the module works in Contao 4 so far. So could you please adjust your composer.json with the following requirements:

```
"php": "~5.4 || ~7.0",
"contao/core-bundle": "^3.5.1 || ~4.1",
"contao-community-alliance/composer-plugin": "~2.4 || ~3.0",
```

Thanks in advance!

**Comment by aschempp** [comment]
Would you be able to create a pull request including the necessary adjustments for the Contao 4.2/4.4 backend?

**Comment by Defcon0** [comment]
I just did a pull request:

https://github.com/terminal42/contao-inserttags/pull/14
