### ISSUE TITLE
Email addresses will not be encrypted

### ISSUE THREAD

**Issue by websolutions-hamburg** [terminal42/contao-inserttags#15]
If I add an email address as replace content, this email address will not be encrypted.
My current workaround is to use this insert tag: `{{email_url::*}}`.

But I think it would be great if email addresses will be automatically encrypted. Because the normal editor will not think about this functionality.

**Comment by aschempp** [comment]
I'm sorry but there are currently no plans to add any new features.
http://unmaintained.tech
