### ISSUE TITLE
Not working in Seitentitel (pageTitle)

### ISSUE THREAD

**Issue by websolutions-hamburg** [terminal42/contao-inserttags#18]
Hello,

the custom insert tags are not working in Seitentitel (pageTitle).

I used Contao 4.4.3.

**Comment by aschempp** [comment]
This is a known limitation of Contao.

**Comment by websolutions-hamburg** [comment]
Intressting, if deactivate this:

```
Ausgabe zwischenspeichern
Klicken Sie hier, wenn dieser Platzhalter vor dem Contao Cache einer Seite angewendet werden soll.
```

It works perfectly. Is this normal, or am I just overlooking something?

**Comment by aschempp** [comment]
Not sure if that feature makes any sense anymore, because insert tag flags were added to Contao. The extension is very much outdated 😉

**Comment by websolutions-hamburg** [comment]
But this extension is the best solution I know for editors, to create and manage customize insert tags. It's so easy and works like a charm!
