### ISSUE TITLE
replaceInsertTags-Hook replaces insert tags from other extensions with empty string

### ISSUE THREAD

**Issue by michb** [terminal42/contao-inserttags#27]
With the change of the `InsertTagsListener` now this will replace all insert tags not starting with `custom`.

As the InsertTagHandler has an early return with `null`
https://github.com/terminal42/contao-inserttags/blob/b4b077a7b06a86e92c9e75dda9f5a28167ce568f/src/InsertTagHandler.php#L32-L38

all insert tags with another first chunk will be replaced with an empty string
https://github.com/terminal42/contao-inserttags/blob/b4b077a7b06a86e92c9e75dda9f5a28167ce568f/src/EventListener/InsertTagsListener.php#L20-L27

**Comment by qzminski** [comment]
Fixed in 2.4.1.
